

export const SET_LOCATION_KEY_SELECTED = " SET_LOCATION_KEY_SELECTED";
export const GET_LOCATION_KEY = "GET_LOCATION_KEY";
export const GET_LOCATION_KEY_SUCCESS =" GET_LOCATION_KEY_SUCCESS"
export const GET_LOCATION_KEY_ERROR = "GET_LOCATION_KEY_ERROR";
export const GET_DAILY_WEATHER = 'GET_DAILY_WEATHER';
export const GET_DAILY_WEATHER_SUCCESS = 'GET_DAILY_WEATHER_SUCCESS';
export const GET_DAILY_WEATHER_ERROR = 'GET_DAILY_WEATHER_ERRORR';